version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  # AfterInstall:
  #   - location: scripts/download_and_load_image.sh
  #     timeout: 300
  #     runas: ec2-user

  ApplicationStart:
    - location: start.sh
      runas: root

  # BeforeInstall:
  #   - location: scripts/stop_containers.sh
  #     timeout: 60
  #     runas: ec2-user
