version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Running unit tests...

  build:
    commands:
      - echo Building Docker image...
      - docker build -t my_first_app .

  post_build:
    commands:
      - echo Saving Docker image...

artifacts:
  files:
    - '**/*'
