version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Running unit tests...

  build:
    commands:
      - echo Building Docker image...
      - nohup dockerd > /tmp/dockerd.log 2>&1 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - docker build -t my_first_app .

  post_build:
    commands:
      - echo Saving Docker image...

artifacts:
  files:
    - '**/*'
