version: '3.8'
services:
  flask-app:
    build:
      context: .
    image: flask-app-image  # Optional: for naming the built image
    container_name: flask_app_container
    ports:
      - "${FLASK_PORT}:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=${FLASK_ENV}
    command: python app.py
