version: '3.8'
services:
  flask-app:
    build: .
    container_name: flask_app_container
    ports:
      - "${FLASK_PORT}:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=${FLASK_ENV}
    command: python run.py
