version: '3.8'
services:
  flask-app:
    build: .
    container_name: flask_app_container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: python run.py
